apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conduit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: conduit.example.com   # update to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: conduit
            port:
              number: 80
