"""add must_change_password to users

Revision ID: 65950fb4dbb3
Revises: bca9b48f2aee
Create Date: 2026-04-03 01:19:11.331647

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65950fb4dbb3"
down_revision = "bca9b48f2aee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "stage_runs", ["stage_run_id"], ["id"])
        batch_op.create_foreign_key(None, "tasks", ["task_id"], ["id"])
        batch_op.create_foreign_key(None, "agent_pools", ["agent_pool_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("persona")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("persona", sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
