"""initial schema

Revision ID: bca9b48f2aee
Revises:
Create Date: 2026-04-03 00:58:49.122109

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bca9b48f2aee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.alter_column("task_id", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_foreign_key(None, "stage_runs", ["stage_run_id"], ["id"])
        batch_op.create_foreign_key(None, "agent_pools", ["agent_pool_id"], ["id"])
        batch_op.create_foreign_key(None, "tasks", ["task_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("persona")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("persona", sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table("task_runs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("task_id", existing_type=sa.VARCHAR(length=64), nullable=True)

    # ### end Alembic commands ###
