{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conduit.fullname" . }}
  namespace: {{ include "conduit.namespace" . }}
  labels:
    {{- include "conduit.labels" . | nindent 4 }}
  annotations:
    # Prevent Helm from showing a diff of secret values in plain text
    helm.sh/resource-policy: keep
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
{{- end }}
